info:
  title: CPPU-ISA
  subtitle: CPPUISA / cppu-isa / seeusec
  author: CPPU-ISA
  url: https://cppu-isa.github.io

defaults:
  favicon: /images/logo.jpg
  logo: /images/logo.jpg
  avatar: /images/logo.jpg

home_banner:
  title: CPPU-ISA
  subtitle:
    text:
      - CPPU-ISA official cybersecurity team website
      - Search us as CPPUISA
      - Search us as cppu-isa
      - Search us as seeusec
  social_links:
    enable: true
    style: default
    links:
      - icon: fa-brands fa-github
        url: https://github.com/CPPU-ISA
      - icon: fa-solid fa-envelope
        url: mailto:cppu_isa@163.com
      - icon: fa-brands fa-weixin
        url: https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzkzMjE4NzU5MA==#wechat_redirect
      - icon: fa-solid fa-at
        url: ""
      - icon: fa-brands fa-telegram
        url: ""
      - icon: /images/custom-icon.svg
        url: ""

global:
  open_graph:
    enable: true
    image: /images/logo.jpg
    description: CPPU-ISA, also known as CPPUISA, cppu-isa, and seeusec, is the official team website for members, glory, writeups, and cybersecurity projects.

articles:
  lazyload: false

navbar:
  links:
    Home:
      path: /
      icon: fa-regular fa-house
    Members:
      path: /statistics/
      icon: fa-regular fa-users
    Glory:
      path: /glory/
      icon: fa-solid fa-trophy
    News:
      path: /news/
      icon: fa-regular fa-newspaper

comment:
  enable: false
